name: TeknetCore
main: io.github.iwilkey.teknetcore.TeknetCore
version: 1.100.D # 1.1.0 LAST
commands:
   lag:
      description: See the current rate at which the server is processing data.
      usage: "Use /lag <no arguments> to see server tps."
   ranks:
      description: Admin rank tools.
      usage: "Use /ranks <command> <args> to administrate ranks."
   cooldown:
      description: See how much time you have until you can send commands or chat.
      usage: "Use /cooldown <no arguments> to see the cooldown time you currently have."
   home:
      description: Teleport back to your home.
      usage: "Use /home <no arguments> to teleport back home."
   sethome:
      description: Set the location of your home.
      usage: "Use /sethome <no arguments> to set the location of your home."
   position:
      description: Save and teleport to locations. Use /position help to get started.
      usage: "Use /position <command> <opt-argument> to utilise tool."